In [22]:
## Iván Andrés Trujillo Abella
## ivantrujillo1229@gmail.com

In [23]:
import numpy as np
import pandas as pd

In [24]:
%%writefile base.csv
nit,condition
1,0
1,0
2,0
2,1
2,0
3,0
3,0
3,0
4,1
5,1
5,1
5,1
5,0
6,1
7,1
7,0

Overwriting base.csv

In [25]:
# In some cases the people have not meet different critera if you fill at least one
# then you can not apply to the program you need remove this perons...

In [26]:
df = pd.read_csv("base.csv")

In [27]:
df['elegible'] =df.groupby(by=['nit'])['condition'].transform('sum')

In [28]:
df

    nit  condition  elegible
0     1          0         0
1     1          0         0
2     2          0         1
3     2          1         1
4     2          0         1
5     3          0         0
6     3          0         0
7     3          0         0
8     4          1         1
9     5          1         3
10    5          1         3
11    5          1         3
12    5          0         3
13    6          1         1
14    7          1         1
15    7          0         1