In [18]:
import pandas  as pd

In [19]:
data =pd.DataFrame({'var1':[10,20,30,40, 50, 60, 70, 80, 90, 100], 'var2':[12,13,412,551,666,3123,5,1,2,1]})

In [20]:
data['decil'] = pd.qcut(data['var1'], 10, labels=False)

In [21]:
data['quartiles'] =   pd.qcut(data['var1'], [0, .25, .5, .75, 1.])

In [22]:
data

   var1  var2  decil      quartiles
0    10    12      0  (9.999, 32.5]
1    20    13      1  (9.999, 32.5]
2    30   412      2  (9.999, 32.5]
3    40   551      3   (32.5, 55.0]
4    50   666      4   (32.5, 55.0]
5    60  3123      5   (55.0, 77.5]
6    70     5      6   (55.0, 77.5]
7    80     1      7  (77.5, 100.0]
8    90     2      8  (77.5, 100.0]
9   100     1      9  (77.5, 100.0]